sonar.projectKey=inkwell
sonar.projectName=Inkwell
sonar.sourceEncoding=UTF-8

sonar.sources=api-gateway,Auth-service,category-service,comment-service,media-service,newsletter-service,notification-service,post-service,service-registry,inkwell-frontend/src
sonar.exclusions=**/target/**,**/node_modules/**,**/dist/**,**/coverage/**

sonar.java.binaries=**/target/classes
sonar.coverage.jacoco.xmlReportPaths=**/target/site/jacoco/jacoco.xml
sonar.javascript.lcov.reportPaths=inkwell-frontend/coverage/lcov.info
