server:
  port: 8086

spring:
  application:
    name: newsletter-service
  datasource:
    url: ${NEWSLETTER_DB_URL:${INKWELL_DB_URL:jdbc:mysql://localhost:3306/inkwell_platform?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}}
    username: ${NEWSLETTER_DB_USERNAME:${INKWELL_DB_USERNAME:root}}
    password: ${NEWSLETTER_DB_PASSWORD:${INKWELL_DB_PASSWORD:admin}}
    driver-class-name: ${NEWSLETTER_DB_DRIVER:${INKWELL_DB_DRIVER:com.mysql.cj.jdbc.Driver}}
  jpa:
    database-platform: ${NEWSLETTER_JPA_DIALECT:${INKWELL_JPA_DIALECT:org.hibernate.dialect.MySQLDialect}}
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:siyateepa9@gmail.com}
    password: ${MAIL_PASSWORD:xdndfdsqjxjrhdnb}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    prefer-ip-address: false

logging:
  config: "${INKWELL_LOG_CONFIG:file:D:/Inkwell/common-logback-spring.xml}"
  file:
    name: ${INKWELL_LOG_DIR:log}/newsletter-service.app.log
  level:
    com.app.newsletterservice: INFO
    org.springframework.security: INFO
    org.springframework.web: INFO

inkwell:
  frontend-url: ${INKWELL_FRONTEND_URL:http://localhost:5173}
  notification:
    kafka:
      topic: ${INKWELL_NOTIFICATION_KAFKA_TOPIC:notification.dispatch.v1}
  auth-service-url: ${INKWELL_AUTH_SERVICE_URL:http://localhost:8081}
  internal-api-key: ${INKWELL_INTERNAL_API_KEY:${AUTH_INTERNAL_API_KEY:ghfyfr7t8hgv7yh}}
  newsletter:
    public-base-url: ${INKWELL_NEWSLETTER_PUBLIC_BASE_URL:http://localhost:8080/newsletter}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
